version: '3.9'
services:
  web:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    networks:
      - default
    volumes:
      - data:/data
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
