version: '3.9'
services:
  web:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - ${HTTP_PORT}:15671
      - ${HTTPS_PORT}:15672
      - ${AMQP_PORT}:5671
      - ${AMQPS_PORT}:5672
      - ${EPMD_PORT}:4369
    networks:
      - default
    volumes:
      - data:/data
    environment:
      - RABBITMQ_DEFAULT_USER=${APP_USER}
      - RABBITMQ_DEFAULT_PASS=${APP_PASS}

networks:
  default:
    name: docker_rabbitmq_network
    driver: bridge

volumes:
  data:
    name: docker_rabbitmq_data
    driver: local
