version: '3.9'
services:
  web:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - ${APP_PORT}:15672
      - ${AMQP_PORT}:5672
    networks:
      - default
    volumes:
      - data:/data
    environment:
      - RABBITMQ_DEFAULT_USER=${APP_USER}
      - RABBITMQ_DEFAULT_PASS=${APP_PASS}

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
